- name: Create directory for database
  file:
    path: /opt/gitlab
    state: directory
    mode: '0755'

- name: Generate file with vars
  template:
    src: docker-compose.yml.j2
    dest: /opt/gitlab/docker-compose.yml


- name: Copy dockerfile
  ansible.builtin.copy:
    src: dockerfile
    dest: /opt/gitlab/dockerfile

- name: Build BDD image
  community.docker.docker_compose_v2:
    project_src: /opt/gitlab/
    state: present
    pull: "missing"
  register: output

- name: Execute gitlab command inside a container
  community.docker.docker_container_exec:
    container: gitlab
    command: /bin/bash -c "gitlab-ctl reconfigure"

- name: Show results
  ansible.builtin.debug:
    var: output.containers[0].Status

- name: Show file content
  ansible.builtin.debug:
    msg: "You can login with root user and password SkGLuP&Ver3rb@IRBBX at {{external_url}}"
