- name: Create directory for database
  file:
    path: /opt/gitlab
    state: directory
    mode: '0755'

- name: Copy env file
  ansible.builtin.copy:
    src: ../../.env
    dest: /opt/gitlab/.env

- name: Copy docker compose file
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/gitlab/docker-compose.yml

- name: Copy dockerfile
  ansible.builtin.copy:
    src: dockerfile
    dest: /opt/gitlab/dockerfile

- name: Build BDD image
  community.docker.docker_compose_v2:
    project_src: /opt/gitlab/
    state: present
    pull: "missing"
  register: output

- name: Execute gitlab command inside a container
  community.docker.docker_container_exec:
    container: gitlab
    command: /bin/bash -c "gitlab-ctl reconfigure"

- name: Show results
  ansible.builtin.debug:
    var: output.containers[0].Status

- name: Show root password
  community.docker.docker_container_exec:
    container: gitlab
    command: cat /etc/gitlab/initial_root_password
  register: file_content

- name: Show file content
  ansible.builtin.debug:
    msg: "{{ file_content.stdout }}"
