version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB:  ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./roles/bdd/files/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - gitlab_network

networks:
  gitlab_network:
    name: gitlab_network
    driver: bridge

volumes:
  pgdata:
