CREATE USER root WITH ENCRYPTED PASSWORD 'root_password';

CREATE DATABASE "all" OWNER vagrant;
CREATE DATABASE dev OWNER vagrant;
CREATE DATABASE stage OWNER vagrant;
CREATE DATABASE prod OWNER vagrant;

GRANT ALL PRIVILEGES ON DATABASE "all" TO vagrant;
GRANT ALL PRIVILEGES ON DATABASE "all" TO root;
CREATE DATABASE root OWNER root;

