
CREATE USER vagrant WITH ENCRYPTED PASSWORD 'password';

CREATE DATABASE all OWNER vagrant;
CREATE DATABASE dev OWNER vagrant;
CREATE DATABASE stage OWNER vagrant;
CREATE DATABASE prod OWNER vagrant;

GRANT ALL PRIVILEGES ON DATABASE all TO vagrant;

