version: '3.8'

services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_database'] = ${POSTGRES_DB}
        gitlab_rails['db_pool'] = 10
        gitlab_rails['db_username'] = ${POSTGRES_USER}
        gitlab_rails['db_password'] = ${POSTGRES_PASSWORD}
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = 5432
    ports:
      - "80:80"
      - "443:443"
      - "2224:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab_network


volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  gitlab_network:
    external: true
