FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=Europe/Paris

RUN apt-get update -y && \
	apt-get install -y curl openssh-server ca-certificates tzdata perl && \
	apt-get clean

RUN curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash

ENV LC_CTYPE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN apt-get install gitlab-ce

EXPOSE 80 443 22 

ENTRYPOINT ["/opt/gitlab/embedded/bin/runsvdir-start"]
CMD ["gitlab-ctl", "reconfigure"]
