- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages for Docker
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{required_packages}}"

- name: Create Docker directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bullseye stable"
    state: present

- name: Install Docker packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items: "{{docker_packages}}"
