- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages for Docker
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{required_packages}}"
  notify: Update apt cache

- name: Create Docker directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bullseye stable"
    state: present
  notify: Update apt cache

- name: Install Docker packages
  apt:
    name: "{{item}}"
    state: present
  with_items: "{{docker_packages}}"
  notify: Updare apt cache

- name: Check docker version
  command: docker --version
  register: docker_version
  ignore_errors: yes

- debug:
    msg: "{{docker_version.stdout}}"


- name: Installer Docker Compose pour Linux x86_64
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.30.2/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Vérifier la version de Docker Compose
  command: docker-compose --version
  register: docker_compose_version
  ignore_errors: yes

- debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"
